# Generated by Django 3.0.7 on 2020-06-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='recordings',
            field=models.FileField(null=True, upload_to='recordings/%Y/%m/%d/'),
        ),
    ]
