# Generated by Django 3.0.7 on 2020-06-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_records_recordings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='recordings',
        ),
    ]
