# Generated by Django 3.0.7 on 2020-06-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_remove_records_recordings'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='continued',
            field=models.BooleanField(default=False),
        ),
    ]
