# Generated by Django 3.0.7 on 2020-06-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_records_continued'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Records',
        ),
    ]
