# Generated by Django 3.0.7 on 2020-06-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_records_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
