# Generated by Django 3.0.7 on 2020-06-28 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200627_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='time',
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 1, 43, 4, 748880)),
        ),
    ]
