# Generated by Django 3.0.7 on 2020-06-29 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200628_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 2, 0, 10, 41328)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
