# Generated by Django 3.0.7 on 2020-06-30 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200629_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='recording',
        ),
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 17, 27, 19, 136518)),
        ),
    ]
