# Generated by Django 3.0.7 on 2020-06-30 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200629_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='continued',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 17, 34, 22, 874448)),
        ),
    ]
