# Generated by Django 3.0.7 on 2020-06-30 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200629_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 17, 55, 18, 43598)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fps',
            field=models.CharField(max_length=2),
        ),
    ]
