# Generated by Django 3.0.7 on 2020-07-01 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200629_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 20, 10, 24, 508841)),
        ),
    ]
