# Generated by Django 3.0.7 on 2020-07-01 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200630_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='continued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 22, 35, 16, 970536)),
        ),
    ]
