# Generated by Django 3.0.7 on 2020-07-01 22:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200701_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 3, 3, 126510, tzinfo=utc)),
        ),
    ]
