# Generated by Django 3.0.7 on 2020-07-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200701_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.CharField(default='16:47:32', max_length=16),
        ),
    ]
