# Generated by Django 3.0.7 on 2020-07-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200701_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=(2020, 7, 1, 17, 5, 46, 2, 183, 1)),
        ),
    ]
