# Generated by Django 3.0.7 on 2020-07-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200701_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=(2020, 7, 1, 17, 8, 14, 2, 183, 1)),
        ),
        migrations.AlterField(
            model_name='records',
            name='releative_path',
            field=models.CharField(default='Kuch bhi', max_length=20),
        ),
    ]
