# Generated by Django 3.0.7 on 2020-07-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200701_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='releative_path',
        ),
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=(2020, 7, 1, 17, 10, 22, 2, 183, 1)),
        ),
    ]
