# Generated by Django 3.0.7 on 2020-07-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20200701_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.CharField(default='17 : 16 : 39', max_length=26),
        ),
    ]
