# Generated by Django 3.0.7 on 2020-07-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200701_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.CharField(default='Not Available', max_length=26),
        ),
    ]
