# Generated by Django 3.0.7 on 2020-07-02 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200701_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='relative_path',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 20, 49, 17, 562811)),
        ),
    ]
