# Generated by Django 3.0.7 on 2020-07-02 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200701_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 13, 29, 55, 474168)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
